// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.auth.passkey@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PASSKEY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PASSKEY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_passkey { () => { "{\"capability_id\":\"lenso.auth.passkey@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"begin_authentication\",\"begin_registration\",\"finish_authentication\",\"finish_registration\",\"list_passkeys\",\"revoke_passkey\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_passkey_client { () => { "{\"capability_id\":\"lenso.auth.passkey@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_passkey_client { () => { "{\"capability_id\":\"lenso.auth.passkey@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const BEGIN_AUTHENTICATION_OPERATION: &str = "begin_authentication";
pub const BEGIN_REGISTRATION_OPERATION: &str = "begin_registration";
pub const FINISH_AUTHENTICATION_OPERATION: &str = "finish_authentication";
pub const FINISH_REGISTRATION_OPERATION: &str = "finish_registration";
pub const LIST_PASSKEYS_OPERATION: &str = "list_passkeys";
pub const REVOKE_PASSKEY_OPERATION: &str = "revoke_passkey";

pub use lenso_contract_runtime::{RawJson, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BeginAuthenticationRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BeginAuthenticationResponse {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "public_key_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub public_key_json: RawJson,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

impl fmt::Debug for BeginAuthenticationResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BeginAuthenticationResponse")
            .field("challenge_id", &self.challenge_id)
            .field("expires_at", &self.expires_at)
            .field("public_key_json", &"<redacted>")
            .field("revision", &self.revision)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum BeginAuthenticationError {
    Forbidden,
    IdempotencyConflict,
    InvalidCredentials,
    InvalidRequest,
    OperationInProgress,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BeginRegistrationRequest {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "user_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub user_name: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BeginRegistrationResponse {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "public_key_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub public_key_json: RawJson,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

impl fmt::Debug for BeginRegistrationResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BeginRegistrationResponse")
            .field("challenge_id", &self.challenge_id)
            .field("expires_at", &self.expires_at)
            .field("public_key_json", &"<redacted>")
            .field("revision", &self.revision)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum BeginRegistrationError {
    Disabled,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    OperationInProgress,
    RevisionConflict,
    TooManyPasskeys,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FinishAuthenticationRequest {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "credential_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_json: RawJson,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
}

impl fmt::Debug for FinishAuthenticationRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("FinishAuthenticationRequest")
            .field("challenge_id", &self.challenge_id)
            .field("credential_json", &"<redacted>")
            .field("idempotency_key", &self.idempotency_key)
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FinishAuthenticationResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "passkey_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for FinishAuthenticationResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("FinishAuthenticationResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("passkey_id", &self.passkey_id)
            .field("revision", &self.revision)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum FinishAuthenticationError {
    ChallengeExpired,
    ChallengeUsed,
    Disabled,
    Forbidden,
    IdempotencyConflict,
    InvalidCredentials,
    InvalidRequest,
    OperationInProgress,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FinishRegistrationRequest {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "credential_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_json: RawJson,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for FinishRegistrationRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("FinishRegistrationRequest")
            .field("challenge_id", &self.challenge_id)
            .field("credential_json", &"<redacted>")
            .field("expected_revision", &self.expected_revision)
            .field("idempotency_key", &self.idempotency_key)
            .field("label", &self.label)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FinishRegistrationResponse {
    #[serde(rename = "passkey")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey: PasskeySummary,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PasskeySummary {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "credential_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_id: String,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "last_used_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_used_at: Option<Timestamp>,
    #[serde(rename = "passkey_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "sign_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sign_count: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FinishRegistrationError {
    ChallengeExpired,
    ChallengeUsed,
    CredentialExists,
    Disabled,
    Forbidden,
    IdempotencyConflict,
    InvalidCredential,
    InvalidRequest,
    OperationInProgress,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListPasskeysRequest {
    #[serde(rename = "include_revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub include_revoked: bool,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListPasskeysResponse {
    #[serde(rename = "passkeys")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkeys: Vec<PasskeySummary>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListPasskeysError {
    Disabled,
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokePasskeyRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "passkey_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokePasskeyResponse {
    #[serde(rename = "passkey_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey_id: String,
    #[serde(rename = "passkey_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub passkey_revision: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokePasskeyError {
    Disabled,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    OperationInProgress,
    PasskeyNotFound,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PasskeyBeginAuthentication;
impl RequestCapability for PasskeyBeginAuthentication {
    type Request = BeginAuthenticationRequest;
    type Response = BeginAuthenticationResponse;
    type DomainError = BeginAuthenticationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != BEGIN_AUTHENTICATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).begin_authentication(context, request)
    }
}

#[derive(Debug)]
pub struct PasskeyBeginRegistration;
impl RequestCapability for PasskeyBeginRegistration {
    type Request = BeginRegistrationRequest;
    type Response = BeginRegistrationResponse;
    type DomainError = BeginRegistrationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != BEGIN_REGISTRATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).begin_registration(context, request)
    }
}

#[derive(Debug)]
pub struct PasskeyFinishAuthentication;
impl RequestCapability for PasskeyFinishAuthentication {
    type Request = FinishAuthenticationRequest;
    type Response = FinishAuthenticationResponse;
    type DomainError = FinishAuthenticationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != FINISH_AUTHENTICATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).finish_authentication(context, request)
    }
}

#[derive(Debug)]
pub struct PasskeyFinishRegistration;
impl RequestCapability for PasskeyFinishRegistration {
    type Request = FinishRegistrationRequest;
    type Response = FinishRegistrationResponse;
    type DomainError = FinishRegistrationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != FINISH_REGISTRATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).finish_registration(context, request)
    }
}

#[derive(Debug)]
pub struct PasskeyListPasskeys;
impl RequestCapability for PasskeyListPasskeys {
    type Request = ListPasskeysRequest;
    type Response = ListPasskeysResponse;
    type DomainError = ListPasskeysError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_PASSKEYS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_passkeys(context, request)
    }
}

#[derive(Debug)]
pub struct PasskeyRevokePasskey;
impl RequestCapability for PasskeyRevokePasskey {
    type Request = RevokePasskeyRequest;
    type Response = RevokePasskeyResponse;
    type DomainError = RevokePasskeyError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_PASSKEY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasskeyRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke_passkey(context, request)
    }
}

impl serde::Serialize for BeginAuthenticationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for BeginAuthenticationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for BeginRegistrationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::TooManyPasskeys => serializer.serialize_str("too_many_passkeys"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for BeginRegistrationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "too_many_passkeys" => Ok(Self::TooManyPasskeys),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for FinishAuthenticationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ChallengeExpired => serializer.serialize_str("challenge_expired"),
            Self::ChallengeUsed => serializer.serialize_str("challenge_used"),
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for FinishAuthenticationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "challenge_expired" => Ok(Self::ChallengeExpired),
                "challenge_used" => Ok(Self::ChallengeUsed),
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for FinishRegistrationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ChallengeExpired => serializer.serialize_str("challenge_expired"),
            Self::ChallengeUsed => serializer.serialize_str("challenge_used"),
            Self::CredentialExists => serializer.serialize_str("credential_exists"),
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidCredential => serializer.serialize_str("invalid_credential"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for FinishRegistrationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "challenge_expired" => Ok(Self::ChallengeExpired),
                "challenge_used" => Ok(Self::ChallengeUsed),
                "credential_exists" => Ok(Self::CredentialExists),
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_credential" => Ok(Self::InvalidCredential),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListPasskeysError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListPasskeysError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokePasskeyError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PasskeyNotFound => serializer.serialize_str("passkey_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokePasskeyError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "passkey_not_found" => Ok(Self::PasskeyNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_begin_authentication_request(value: &BeginAuthenticationRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_authentication_request(wire: &str) -> Result<BeginAuthenticationRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_begin_authentication_response(value: &BeginAuthenticationResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_authentication_response(wire: &str) -> Result<BeginAuthenticationResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_begin_authentication_error(value: &BeginAuthenticationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_authentication_error(wire: &str) -> Result<BeginAuthenticationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_begin_registration_request(value: &BeginRegistrationRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_registration_request(wire: &str) -> Result<BeginRegistrationRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_begin_registration_response(value: &BeginRegistrationResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_registration_response(wire: &str) -> Result<BeginRegistrationResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_begin_registration_error(value: &BeginRegistrationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_begin_registration_error(wire: &str) -> Result<BeginRegistrationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_finish_authentication_request(value: &FinishAuthenticationRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_authentication_request(wire: &str) -> Result<FinishAuthenticationRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_finish_authentication_response(value: &FinishAuthenticationResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_authentication_response(wire: &str) -> Result<FinishAuthenticationResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_finish_authentication_error(value: &FinishAuthenticationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_authentication_error(wire: &str) -> Result<FinishAuthenticationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_finish_registration_request(value: &FinishRegistrationRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_registration_request(wire: &str) -> Result<FinishRegistrationRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_finish_registration_response(value: &FinishRegistrationResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_registration_response(wire: &str) -> Result<FinishRegistrationResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_finish_registration_error(value: &FinishRegistrationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_finish_registration_error(wire: &str) -> Result<FinishRegistrationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_passkeys_request(value: &ListPasskeysRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_passkeys_request(wire: &str) -> Result<ListPasskeysRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_passkeys_response(value: &ListPasskeysResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_passkeys_response(wire: &str) -> Result<ListPasskeysResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_passkeys_error(value: &ListPasskeysError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_passkeys_error(wire: &str) -> Result<ListPasskeysError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_passkey_request(value: &RevokePasskeyRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_passkey_request(wire: &str) -> Result<RevokePasskeyRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_passkey_response(value: &RevokePasskeyResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_passkey_response(wire: &str) -> Result<RevokePasskeyResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_passkey_error(value: &RevokePasskeyError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_passkey_error(wire: &str) -> Result<RevokePasskeyError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPasskeyBeginAuthenticationResult {
    fn __lenso_into_result(self) -> Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyBeginAuthenticationResult for Result<BeginAuthenticationResponse, BeginAuthenticationError> {
    fn __lenso_into_result(self) -> Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyBeginAuthenticationResult for Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyBeginAuthenticationResult for Result<BeginAuthenticationResponse, lenso_plugin_authoring::PluginError<BeginAuthenticationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyBeginAuthenticationResult for Result<BeginAuthenticationResponse, PasskeyBeginAuthenticationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<BeginAuthenticationResponse, BeginAuthenticationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyBeginAuthenticationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyBeginAuthenticationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasskeyBeginRegistrationResult {
    fn __lenso_into_result(self) -> Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyBeginRegistrationResult for Result<BeginRegistrationResponse, BeginRegistrationError> {
    fn __lenso_into_result(self) -> Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyBeginRegistrationResult for Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyBeginRegistrationResult for Result<BeginRegistrationResponse, lenso_plugin_authoring::PluginError<BeginRegistrationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyBeginRegistrationResult for Result<BeginRegistrationResponse, PasskeyBeginRegistrationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<BeginRegistrationResponse, BeginRegistrationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyBeginRegistrationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyBeginRegistrationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasskeyFinishAuthenticationResult {
    fn __lenso_into_result(self) -> Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyFinishAuthenticationResult for Result<FinishAuthenticationResponse, FinishAuthenticationError> {
    fn __lenso_into_result(self) -> Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyFinishAuthenticationResult for Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyFinishAuthenticationResult for Result<FinishAuthenticationResponse, lenso_plugin_authoring::PluginError<FinishAuthenticationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyFinishAuthenticationResult for Result<FinishAuthenticationResponse, PasskeyFinishAuthenticationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<FinishAuthenticationResponse, FinishAuthenticationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyFinishAuthenticationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyFinishAuthenticationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasskeyFinishRegistrationResult {
    fn __lenso_into_result(self) -> Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyFinishRegistrationResult for Result<FinishRegistrationResponse, FinishRegistrationError> {
    fn __lenso_into_result(self) -> Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyFinishRegistrationResult for Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyFinishRegistrationResult for Result<FinishRegistrationResponse, lenso_plugin_authoring::PluginError<FinishRegistrationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyFinishRegistrationResult for Result<FinishRegistrationResponse, PasskeyFinishRegistrationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<FinishRegistrationResponse, FinishRegistrationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyFinishRegistrationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyFinishRegistrationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasskeyListPasskeysResult {
    fn __lenso_into_result(self) -> Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyListPasskeysResult for Result<ListPasskeysResponse, ListPasskeysError> {
    fn __lenso_into_result(self) -> Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyListPasskeysResult for Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyListPasskeysResult for Result<ListPasskeysResponse, lenso_plugin_authoring::PluginError<ListPasskeysError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyListPasskeysResult for Result<ListPasskeysResponse, PasskeyListPasskeysInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListPasskeysResponse, ListPasskeysError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyListPasskeysInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyListPasskeysInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPasskeyRevokePasskeyResult {
    fn __lenso_into_result(self) -> Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure>;
}
impl __LensoIntoPasskeyRevokePasskeyResult for Result<RevokePasskeyResponse, RevokePasskeyError> {
    fn __lenso_into_result(self) -> Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPasskeyRevokePasskeyResult for Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure> { self }
}
impl __LensoIntoPasskeyRevokePasskeyResult for Result<RevokePasskeyResponse, lenso_plugin_authoring::PluginError<RevokePasskeyError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPasskeyRevokePasskeyResult for Result<RevokePasskeyResponse, PasskeyRevokePasskeyInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokePasskeyResponse, RevokePasskeyError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PasskeyRevokePasskeyInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PasskeyRevokePasskeyInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PasskeyProvider: fmt::Debug + 'static {
    fn begin_authentication(&self, context: InvocationContext, request: BeginAuthenticationRequest) -> NativeRequestFuture<PasskeyBeginAuthentication>;
    fn begin_registration(&self, context: InvocationContext, request: BeginRegistrationRequest) -> NativeRequestFuture<PasskeyBeginRegistration>;
    fn finish_authentication(&self, context: InvocationContext, request: FinishAuthenticationRequest) -> NativeRequestFuture<PasskeyFinishAuthentication>;
    fn finish_registration(&self, context: InvocationContext, request: FinishRegistrationRequest) -> NativeRequestFuture<PasskeyFinishRegistration>;
    fn list_passkeys(&self, context: InvocationContext, request: ListPasskeysRequest) -> NativeRequestFuture<PasskeyListPasskeys>;
    fn revoke_passkey(&self, context: InvocationContext, request: RevokePasskeyRequest) -> NativeRequestFuture<PasskeyRevokePasskey>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_passkey {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPasskey;
        impl $crate::PasskeyProvider for $plugin {
        fn begin_authentication(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::BeginAuthenticationRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyBeginAuthentication> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::begin_authentication(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyBeginAuthenticationResult::__lenso_into_result(result)
            })
        }
        fn begin_registration(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::BeginRegistrationRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyBeginRegistration> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::begin_registration(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyBeginRegistrationResult::__lenso_into_result(result)
            })
        }
        fn finish_authentication(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::FinishAuthenticationRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyFinishAuthentication> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::finish_authentication(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyFinishAuthenticationResult::__lenso_into_result(result)
            })
        }
        fn finish_registration(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::FinishRegistrationRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyFinishRegistration> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::finish_registration(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyFinishRegistrationResult::__lenso_into_result(result)
            })
        }
        fn list_passkeys(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::ListPasskeysRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyListPasskeys> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_passkeys(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyListPasskeysResult::__lenso_into_result(result)
            })
        }
        fn revoke_passkey(&self, context: __LensoNativeSupportPasskey::InvocationContext, request: $crate::RevokePasskeyRequest) -> __LensoNativeSupportPasskey::NativeRequestFuture<$crate::PasskeyRevokePasskey> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke_passkey(&plugin, context, request).await;
                $crate::__LensoIntoPasskeyRevokePasskeyResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct PasskeyRequestEndpoint { provider: Rc<dyn PasskeyProvider> }

#[derive(Debug)]
pub struct PasskeyEndpoint<P: PasskeyProvider> { provider: Rc<P>, request_endpoint: PasskeyRequestEndpoint }
impl<P: PasskeyProvider> PasskeyEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PasskeyProvider> = provider.clone();
        Self { provider, request_endpoint: PasskeyRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PasskeyProvider> NativeRequestEndpoint for PasskeyEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        BEGIN_AUTHENTICATION_OPERATION,
        BEGIN_REGISTRATION_OPERATION,
        FINISH_AUTHENTICATION_OPERATION,
        FINISH_REGISTRATION_OPERATION,
        LIST_PASSKEYS_OPERATION,
        REVOKE_PASSKEY_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            BEGIN_AUTHENTICATION_OPERATION => {
                let Ok(request) = request.downcast::<BeginAuthenticationRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).begin_authentication(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            BEGIN_REGISTRATION_OPERATION => {
                let Ok(request) = request.downcast::<BeginRegistrationRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).begin_registration(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            FINISH_AUTHENTICATION_OPERATION => {
                let Ok(request) = request.downcast::<FinishAuthenticationRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).finish_authentication(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            FINISH_REGISTRATION_OPERATION => {
                let Ok(request) = request.downcast::<FinishRegistrationRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).finish_registration(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_PASSKEYS_OPERATION => {
                let Ok(request) = request.downcast::<ListPasskeysRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_passkeys(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_PASSKEY_OPERATION => {
                let Ok(request) = request.downcast::<RevokePasskeyRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke_passkey(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_passkey {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PasskeyEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_passkey {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_passkey!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct PasskeyClient {
    begin_authentication: NativeRequestHandle<PasskeyBeginAuthentication>,
    begin_registration: NativeRequestHandle<PasskeyBeginRegistration>,
    finish_authentication: NativeRequestHandle<PasskeyFinishAuthentication>,
    finish_registration: NativeRequestHandle<PasskeyFinishRegistration>,
    list_passkeys: NativeRequestHandle<PasskeyListPasskeys>,
    revoke_passkey: NativeRequestHandle<PasskeyRevokePasskey>,
}
impl PasskeyClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn begin_authentication(&self, request: BeginAuthenticationRequest) -> Result<BeginAuthenticationResponse, PasskeyBeginAuthenticationInvocationError> {
        self.begin_authentication.invoke(BEGIN_AUTHENTICATION_OPERATION, request).await
            .map_err(PasskeyBeginAuthenticationInvocationError::Runtime)?
            .map_err(PasskeyBeginAuthenticationInvocationError::Domain)
    }

    pub async fn begin_authentication_with_context(&self, context: InvocationContext, request: BeginAuthenticationRequest) -> Result<BeginAuthenticationResponse, PasskeyBeginAuthenticationInvocationError> {
        self.begin_authentication.invoke_with_context(BEGIN_AUTHENTICATION_OPERATION, context, request).await
            .map_err(PasskeyBeginAuthenticationInvocationError::Runtime)?
            .map_err(PasskeyBeginAuthenticationInvocationError::Domain)
    }

    pub async fn begin_registration(&self, request: BeginRegistrationRequest) -> Result<BeginRegistrationResponse, PasskeyBeginRegistrationInvocationError> {
        self.begin_registration.invoke(BEGIN_REGISTRATION_OPERATION, request).await
            .map_err(PasskeyBeginRegistrationInvocationError::Runtime)?
            .map_err(PasskeyBeginRegistrationInvocationError::Domain)
    }

    pub async fn begin_registration_with_context(&self, context: InvocationContext, request: BeginRegistrationRequest) -> Result<BeginRegistrationResponse, PasskeyBeginRegistrationInvocationError> {
        self.begin_registration.invoke_with_context(BEGIN_REGISTRATION_OPERATION, context, request).await
            .map_err(PasskeyBeginRegistrationInvocationError::Runtime)?
            .map_err(PasskeyBeginRegistrationInvocationError::Domain)
    }

    pub async fn finish_authentication(&self, request: FinishAuthenticationRequest) -> Result<FinishAuthenticationResponse, PasskeyFinishAuthenticationInvocationError> {
        self.finish_authentication.invoke(FINISH_AUTHENTICATION_OPERATION, request).await
            .map_err(PasskeyFinishAuthenticationInvocationError::Runtime)?
            .map_err(PasskeyFinishAuthenticationInvocationError::Domain)
    }

    pub async fn finish_authentication_with_context(&self, context: InvocationContext, request: FinishAuthenticationRequest) -> Result<FinishAuthenticationResponse, PasskeyFinishAuthenticationInvocationError> {
        self.finish_authentication.invoke_with_context(FINISH_AUTHENTICATION_OPERATION, context, request).await
            .map_err(PasskeyFinishAuthenticationInvocationError::Runtime)?
            .map_err(PasskeyFinishAuthenticationInvocationError::Domain)
    }

    pub async fn finish_registration(&self, request: FinishRegistrationRequest) -> Result<FinishRegistrationResponse, PasskeyFinishRegistrationInvocationError> {
        self.finish_registration.invoke(FINISH_REGISTRATION_OPERATION, request).await
            .map_err(PasskeyFinishRegistrationInvocationError::Runtime)?
            .map_err(PasskeyFinishRegistrationInvocationError::Domain)
    }

    pub async fn finish_registration_with_context(&self, context: InvocationContext, request: FinishRegistrationRequest) -> Result<FinishRegistrationResponse, PasskeyFinishRegistrationInvocationError> {
        self.finish_registration.invoke_with_context(FINISH_REGISTRATION_OPERATION, context, request).await
            .map_err(PasskeyFinishRegistrationInvocationError::Runtime)?
            .map_err(PasskeyFinishRegistrationInvocationError::Domain)
    }

    pub async fn list_passkeys(&self, request: ListPasskeysRequest) -> Result<ListPasskeysResponse, PasskeyListPasskeysInvocationError> {
        self.list_passkeys.invoke(LIST_PASSKEYS_OPERATION, request).await
            .map_err(PasskeyListPasskeysInvocationError::Runtime)?
            .map_err(PasskeyListPasskeysInvocationError::Domain)
    }

    pub async fn list_passkeys_with_context(&self, context: InvocationContext, request: ListPasskeysRequest) -> Result<ListPasskeysResponse, PasskeyListPasskeysInvocationError> {
        self.list_passkeys.invoke_with_context(LIST_PASSKEYS_OPERATION, context, request).await
            .map_err(PasskeyListPasskeysInvocationError::Runtime)?
            .map_err(PasskeyListPasskeysInvocationError::Domain)
    }

    pub async fn revoke_passkey(&self, request: RevokePasskeyRequest) -> Result<RevokePasskeyResponse, PasskeyRevokePasskeyInvocationError> {
        self.revoke_passkey.invoke(REVOKE_PASSKEY_OPERATION, request).await
            .map_err(PasskeyRevokePasskeyInvocationError::Runtime)?
            .map_err(PasskeyRevokePasskeyInvocationError::Domain)
    }

    pub async fn revoke_passkey_with_context(&self, context: InvocationContext, request: RevokePasskeyRequest) -> Result<RevokePasskeyResponse, PasskeyRevokePasskeyInvocationError> {
        self.revoke_passkey.invoke_with_context(REVOKE_PASSKEY_OPERATION, context, request).await
            .map_err(PasskeyRevokePasskeyInvocationError::Runtime)?
            .map_err(PasskeyRevokePasskeyInvocationError::Domain)
    }
}

impl CapabilityClient for PasskeyClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            begin_authentication: dependencies.one::<PasskeyBeginAuthentication>()?,
            begin_registration: dependencies.one::<PasskeyBeginRegistration>()?,
            finish_authentication: dependencies.one::<PasskeyFinishAuthentication>()?,
            finish_registration: dependencies.one::<PasskeyFinishRegistration>()?,
            list_passkeys: dependencies.one::<PasskeyListPasskeys>()?,
            revoke_passkey: dependencies.one::<PasskeyRevokePasskey>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PasskeyClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    begin_authentication: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyBeginAuthentication>()?,
                    begin_registration: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyBeginRegistration>()?,
                    finish_authentication: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyFinishAuthentication>()?,
                    finish_registration: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyFinishRegistration>()?,
                    list_passkeys: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyListPasskeys>()?,
                    revoke_passkey: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PasskeyRevokePasskey>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyBeginAuthenticationInvocationError {
    Domain(BeginAuthenticationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyBeginRegistrationInvocationError {
    Domain(BeginRegistrationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyFinishAuthenticationInvocationError {
    Domain(FinishAuthenticationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyFinishRegistrationInvocationError {
    Domain(FinishRegistrationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyListPasskeysInvocationError {
    Domain(ListPasskeysError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasskeyRevokePasskeyInvocationError {
    Domain(RevokePasskeyError),
    Runtime(RuntimeFailure),
}
